---
title: "grd"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{grd}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(hyperion)
library(dplyr)
```

```{r}
get_gradients("test_data/grd/bql.grd")  %>% 
  slice_tail(n = 1) %>% 
  summarize(any_zero = any(across(everything(), ~ .x == 0))) %>% 
  pull(any_zero) %>% 
  as.numeric()
```

```{r}
devtools::load_all()

mod <- read_model(normalizePath("~/Documents/voodoo-conjurer-testing/ANALYSES/run2"))
mod$omega_blocks

get_gradients(normalizePath("~/Documents/voodoo-conjurer-testing/ANALYSES/run2/"), comment_type = "type1")

get_gradients("test_data/models/onecmt/run001/")

read_model("test_data/models/onecmt/run001")
get_gradients("test_data/models/onecmt/run001", comment_type = "type1")

get_gradients("test_data/models/onecmt/run001/run001.grd")
```


```{r}
get_gradients("test_data/models/onecmt/run002/")


get_gradients("test_data/models/onecmt/run002.mod")


get_gradients("test_data/models/onecmt/run002/run002.grd")

get_gradients("test_data/models/onecmt/run002_metadata.json")
```
