---
title: "lst"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lst}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(hyperion)

test_data_dir <- system.file("extdata", package = "hyperion")
```

# Parse lst
```{r}
get_run_info(file.path(test_data_dir, "lst", "bql.lst"))$run_details
```


```{r}
get_run_info(file.path(test_data_dir, "lst", "bql.lst"))$run_heuristics
```

```{r}
get_run_info(file.path(test_data_dir, "lst", "saemimp.lst"))$run_details
```
```{r}
get_run_info(file.path(test_data_dir, "lst", "saemimp.lst"))$run_heuristics
```

```{r}
get_run_info(file.path(test_data_dir, "models", "onecmt", "run001"))

get_run_info(file.path(test_data_dir, "models", "onecmt", "run001.mod"))

get_run_info(file.path(test_data_dir, "models", "onecmt", "run001", "run001.lst"))
```

```{r}
get_run_info(file.path(test_data_dir, "models", "onecmt", "run002_metadata.json"))
```

```{r}
mod_sum <- summary(file.path(test_data_dir, "models", "onecmt", "run002"))
class(mod_sum)
mod_sum
```


