---
title: "parameter-tables"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{parameter-tables}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(hyperion)
library(gt)

model_dir <- "test_data/models/onecmt"
model_run <- "run003"
```

```{r}
spec <- TableSpec(
  display_transforms = list(omega = c("cv")),
  sections = section_rules(
    kind == "THETA" ~ "Structural model parameters",
    kind == "OMEGA" & diagonal ~ "Interindividual variance parameters",
    kind == "OMEGA" & !diagonal ~ "Interindividual covariance parameters",
    kind == "SIGMA" ~ "Residual variance",
    TRUE ~ "Other"
  )
)

info <- get_model_parameter_info(
  file.path(model_dir, model_run),
  normalizePath("~/Documents/hyperion/inst/lookup.yaml")
)

info@sigma$`SIGMA(1,1)`@name <- "Additive Error"
info@sigma$`SIGMA(2,2)`@name <- "Proportional Error"

mod_sum <- get_model_summary(file.path(model_dir, model_run))

get_parameters(file.path(model_dir, model_run)) |>
  apply_table_spec(info, spec) |>
  add_summary_rows(mod_sum) |>
  add_display_names(info) |>
  add_description_column(info) |>
	make_parameter_table()
```
Removing columns with `@drop_columns` field
```{r}
spec@drop_columns <- "unit"
get_parameters(file.path(model_dir, model_run)) |>
  apply_table_spec(info, spec) |>
  add_summary_rows(mod_sum) |>
  make_parameter_table()
```

```{r}
spec@drop_columns <- c("unit", "shrinkage")
get_parameters(file.path(model_dir, model_run)) |>
  apply_table_spec(info, spec) |>
  add_summary_rows(mod_sum) |>
  make_parameter_table()
```

# Structural parameters only
```{r}
sp_spec <- TableSpec(
  sections = section_rules(
    kind == "THETA" ~ "Structural model parameters",
    TRUE ~ "Other"
  ),
  row_filter = filter_rules(
    kind == "THETA"
  ),
  drop_columns = "shrinkage"
)

get_parameters(file.path(model_dir, model_run)) |>
  apply_table_spec(info, sp_spec) |>
  make_parameter_table()
```

# Random Effect Parameters only
```{r}
re_spec <- TableSpec(
  sections = section_rules(
    kind == "OMEGA" ~ "Random Effect Parameters",
    kind == "SIGMA" ~ "Residual Error",
    TRUE ~ "Other"
  ),
  row_filter = filter_rules(
    kind != "THETA"
  ),
  drop_columns = "unit",
)

get_parameters(file.path(model_dir, model_run)) |>
  apply_table_spec(info, re_spec) |>
  make_parameter_table()
```

# Confidence Interval level
```{r}
spec <- TableSpec(
  display_transforms = list(omega = c("cv")),
  sections = section_rules(
    kind == "THETA" ~ "Structural model parameters",
    kind == "OMEGA" & diagonal ~ "Interindividual variance parameters",
    kind == "OMEGA" & !diagonal ~ "Interindividual covariance parameters",
    kind == "SIGMA" ~ "Residual variance",
    TRUE ~ "Other"
  ),
  ci_level = 0.90
)

mod_sum <- get_model_summary(file.path(model_dir, model_run))
info <- get_model_parameter_info(file.path(model_dir, model_run))

get_parameters(file.path(model_dir, model_run)) |>
  apply_table_spec(info, spec) |>
  add_summary_rows(mod_sum) |>
  make_parameter_table()
```
