# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the miniextendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate: rebuild the package (R CMD INSTALL or devtools::install).
# nolint start
# nocov start

# Generated from Rust fn `set_panic_message` (core/mod.rs:18:8)
#' @title Suppress panic messages from pharos
#' @return NULL
#' @export
#' @source Generated by miniextendr from Rust fn `set_panic_message`
set_panic_message <- function() {
  .val <- .Call(C_set_panic_message, .call = match.call())
  if (inherits(.val, "rust_error_value") && isTRUE(attr(.val, "__rust_error__"))) {
    stop(structure(
      class = c("rust_error", "simpleError", "error", "condition"),
      list(message = .val$error, call = .val$call %||% sys.call(), kind = .val$kind)
    ))
  }
  invisible(.val)
}

# Generated from Rust fn `find_pharos_config_file` (core/mod.rs:27:8)
#' @title Find the pharos config file path
#' @return path to pharos.toml, or a message if not found
#' @export
#' @source Generated by miniextendr from Rust fn `find_pharos_config_file`
find_pharos_config_file <- function() {
  .val <- .Call(C_find_pharos_config_file, .call = match.call())
  if (inherits(.val, "rust_error_value") && isTRUE(attr(.val, "__rust_error__"))) {
    stop(structure(
      class = c("rust_error", "simpleError", "error", "condition"),
      list(message = .val$error, call = .val$call %||% sys.call(), kind = .val$kind)
    ))
  }
  .val
}

# Generated from Rust fn `init` (init.rs:23:8)
#' @title Initializes pharos
#' @param config_path path to where pharos.toml is saved (should be colocated to where pharos is
#' run from)
#' @return nothing
#' @rdname init
#' @export
#' @examples \dontrun{
#' init("model/nonmem/submission-log/pharos.toml")
#' }
#' @source Generated by miniextendr from Rust fn `init`
init <- function(config_path) {
  stopifnot(
    "'config_path' must be character" = is.character(config_path),
    "'config_path' must have length 1" = length(config_path) == 1L
  )
  .val <- .Call(C_init, .call = match.call(), config_path)
  if (inherits(.val, "rust_error_value") && isTRUE(attr(.val, "__rust_error__"))) {
    stop(structure(
      class = c("rust_error", "simpleError", "error", "condition"),
      list(message = .val$error, call = .val$call %||% sys.call(), kind = .val$kind)
    ))
  }
  invisible(.val)
}

# nocov end
# nolint end
