use_lockfile = false

[project]
name = "hyperion"
r_version = "4.5"

repositories = [
		{alias = "prism", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2025-09-29" },
		{alias = "ppm", url = "https://packagemanager.posit.co/cran/latest"},
		{alias = "CRAN", url = "https://cran.r-project.org"},
]

dependencies = [
		"devtools",
		"rextendr",
		{name = "hyperion", path = ".", dependencies_only = true, install_suggestions = true},
		{name = "gdtools", repository = "CRAN" },
]
