[package]
name = "hyperion-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
# R Integration (needed for extendr macros in modules)
extendr-api = { workspace = true }
hyperion-nonmem = { path = "../nonmem" }
hyperion-core = { path = "../core" }

which = "8.0.0"

# Pharos components
nonmem = { workspace = true }
scheduler = { workspace = true }
