# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_hyperion_wrappers", use_symbols = TRUE, package_name = "hyperion")

#' @usage NULL
#' @useDynLib hyperion, .registration = TRUE
NULL

set_panic_message <- function() invisible(.Call(wrap__set_panic_message))

#' Gets parameter estimates from model run
#'
#' @param path path to model file, model output directory, ext file or metadata json file.
#' @param hide_off_diagonal_params boolean, if TRUE will not display the unfixed off-diagonal
#' estimated parameters
#' @param only_method character, filter for getting estimates from specified method only
#' @param only_last boolean, for grabbing only last estimation method parameters
#' @param columns character vector of columns to include in resulting dataframe. Default: c("kind", "name", "value", "stderr", "fixed").
#' Available columns: "kind", "name", "value", "stderr", "rse", "shrinkage", "fixed", "table_idx", "method"
#'
#' @return data.frame of parameter estimates
#' @export
#'
#' @examples \dontrun{
#' get_parameter_estimates("model/nonmem/run001/run001.ext")
#' }
get_parameter_estimates <- function(path, hide_off_diagonal_params = FALSE, only_method = NULL, only_last = TRUE, columns = c("kind", "name", "value", "stderr", "shrinkage", "fixed")) .Call(wrap__get_parameter_estimates_wrap, path, hide_off_diagonal_params, only_method, only_last, columns)

#' Reads ext file
#'
#' @param path path to model file, model output directory, ext file or metadata json file.
#' @param line_prefixes character vector for lines to filter for
#' @param parameters_only bool if true removes ITERATION and OBJ column, default false
#' @param only_method character, filter for getting estimates from specified method only
#' @param only_last boolean, for grabbing only last estimation method parameters
#'
#' @return data.frame of ext file
#' @export
#'
#' @examples \dontrun{
#' read_ext_file("model/nonmem/run001/run001.ext")
#' }
read_ext_file <- function(path, line_prefixes = NULL, parameters_only = FALSE, only_method = NULL, only_last = TRUE) .Call(wrap__read_ext_file, path, line_prefixes, parameters_only, only_method, only_last)

#' Gets gradients of pararmeters during modeling
#'
#' @param path path to model file, model output directory, grd file or metadata json file.
#' @param comment_type character of control stream comment type. type1 currently supported.
#' @param only_method character, filter for getting estimates from specified method only
#' @param only_last boolean, for grabbing only last estimation method parameters
#'
#' @return data.frame of gradients
#' @export
#'
#' @examples \dontrun{
#' get_gradients("model/nonmem/run001/run001.grd")
#' }
get_gradients <- function(path, comment_type = NULL, only_method = NULL, only_last = TRUE) .Call(wrap__get_gradients, path, comment_type, only_method, only_last)

#' Gets ETA shrinkage metrics from .shk file
#'
#' @param path path to model file, model output directory, shk file or metadata json file.
#'
#' @return data.frame of ETA shrinkage metrics
#' @export
#'
#' @examples \dontrun{
#' get_eta_shrinkage("model/nonmem/run001/run001.shk")
#' }
get_eta_shrinkage <- function(path) .Call(wrap__get_eta_shrinkage, path)

#' Gets EPS shrinkage metrics from .shk file
#'
#' @param path path to model file, model output directory, shk file or metadata json file.
#'
#' @return data.frame of EPS shrinkage metrics
#' @export
#'
#' @examples \dontrun{
#' get_eps_shrinkage("model/nonmem/run001/run001.shk")
#' }
get_eps_shrinkage <- function(path) .Call(wrap__get_eps_shrinkage, path)

#' Gets model object
#'
#' @param path path to mod file, model output directory, or metadata.json file
#'
#' @return hyperion_model S3 object
#' @export
#'
#' @examples \dontrun{
#' read_model("model/nonmem/run001")
#' }
read_model <- function(path) .Call(wrap__read_model, path)

#' Checks model dataset
#'
#' @param model list of model object from `read_model`
#' @param model_dir directory of model output //TODO check this
#'
#' @return nothing //todo maybe a true/false?
#' @export
#'
#' @examples \dontrun{
#' model <- read_model("model/nonmem/run001.mod")
#' model |> check_dataset("model/nonmem/run001")
#' }
check_dataset <- function(model, model_dir) .Call(wrap__check_dataset, model, model_dir)

#' Copies model file to new model file
#'
#' @param from path to model file to copy
#' @param to path to model file to write to
#' @param overwrite boolean, wheter to overwrite existing model. Default FALSE
#' @param ext_file path to ext file to use for parameter estimates
#' @param update todo
#' @param jitter todo
#' @param jitter_excluded todo
#' @param seed todo
#' @param description Description of model in metadata file
#' @param no_metadata boolean, if true, does not create metadatafile, default FALSE
#'
#' @return path to new model file (invisible) todo
#' @export
#'
#' @examples \dontrun{
#' copy_model(from = "model/nonmem/run001.mod", to = "model/nonmem/run002.mod")
#' }
copy_model <- function(from, to, overwrite = FALSE, ext_file = NULL, update = 'none', jitter = NULL, jitter_excluded = NULL, seed = NULL, description = NULL, no_metadata = FALSE) .Call(wrap__copy_model_wrap, from, to, overwrite, ext_file, update, jitter, jitter_excluded, seed, description, no_metadata)

#' Gets model run summary
#'
#' @param directory path to model run output directory containing .ext, .lst files
#' @param hide_off_diagonal_params boolean, if TRUE will not display the unfixed off-diagonal
#' estimated parameters
#' @param comment_type string of control stream comments types. Type1 or NULL
#' @param columns character vector of columns to include in resulting dataframe. Default: c("name", "value", "stderr", "rse", "shrinkage", "kind").
#' Available columns: "kind", "name", "value", "stderr", "rse", "shrinkage", "fixed", "table_idx", "method", random_effect
#'
#' @return list of data.frames of run details, run heuristics, and parameter estimates
#' @export
#'
#' @examples \dontrun{
#' get_model_summary("model/nonmem/run001")
#' }
get_model_summary <- function(directory, hide_off_diagonal_params = FALSE, comment_type = NULL, columns = c("name", "random_effect", "value", "stderr", "rse", "shrinkage", "kind")) .Call(wrap__get_model_summary, directory, hide_off_diagonal_params, comment_type, columns)

#' Parses lst file for run details and heuristics
#'
#' @param path path to model file, model output directory, lst file or metadata json file.
#'
#' @return list of data.frames of run details and run heuristics
#' @export
#'
#' @examples \dontrun{
#' get_run_info("model/nonmem/run001/run001.lst")
#' }
get_run_info <- function(path) .Call(wrap__get_run_info, path)

#' Checks mod file for nmtran errors
#'
#' @param model_path path to nonmem model file
#' @param config_path path to pharos.toml config file
#'
#' @return NULL
#' @export
#'
#' @examples \dontrun{
#' check_model("model/nonmem/1001.mod")
#' }
check_model <- function(model_path, config_path) .Call(wrap__check_model_wrap, model_path, config_path)

#' Get's model lineage
#'
#' @param model_dir path to directory containing all models
#'
#' @return lineage tree //todo what is this?
#' @export
#'
#' @examples \dontrun{
#' get_model_lineage("model/nonmem/")
#' }
get_model_lineage <- function(model_dir) .Call(wrap__get_model_lineage, model_dir)

#' Initializes pharos
#'
#' @param config_path path to where pharos.toml is saved (should be colocated to where pharos is
#' run from)
#'
#' @return nothing
#' @export
#'
#' @examples \dontrun{
#' init("model/nonmem/submission-log/pharos.toml")
#' }
init <- function(config_path) .Call(wrap__init, config_path)


# nolint end
