# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_hyperion_wrappers", use_symbols = TRUE, package_name = "hyperion")

#' @usage NULL
#' @useDynLib hyperion, .registration = TRUE
NULL

#' Initializes pharos
#'
#' @param config_path path to where pharos.toml is saved (should be colocated to where pharos is
#' run from)
#'
#' @return nothing
#' @export
#'
#' @examples \dontrun{
#' init("model/nonmem/submission-log/pharos.toml")
#' }
init <- function(config_path) .Call(wrap__init, config_path)

set_panic_message <- function() .Call(wrap__set_panic_message)

find_pharos_config_file <- function() .Call(wrap__find_pharos_config_file)

#' Gets model object
#'
#' @param path path to mod file, model output directory, or metadata.json file
#'
#' @return hyperion_nonmem_model S3 object
#' @export
#'
#' @examples \dontrun{
#' read_model("model/nonmem/run001")
#' }
read_model <- function(path) .Call(wrap__read_model, path)

#' Checks model dataset
#'
#' @param model list of model object from `read_model`
#' @param model_dir directory of model output //TODO check this
#'
#' @return nothing //todo maybe a true/false?
#' @export
#'
#' @examples \dontrun{
#' model <- read_model("model/nonmem/run001.mod")
#' model |> check_dataset("model/nonmem/run001")
#' }
check_dataset <- function(model, model_dir) .Call(wrap__check_dataset, model, model_dir)

#' Copies model file to new model file
#'
#' @param from path to model file to copy
#' @param to path to model file to write to
#' @param overwrite boolean, wheter to overwrite existing model. Default FALSE
#' @param ext_file path to ext file to use for parameter estimates
#' @param update character or character vector specifying which parameters to update from ext file.
#' Options: "all", "none", "theta", "omega", "sigma". Examples: "all" or c("theta", "omega")
#' @param jitter numeric value or named numeric vector for parameter jittering using uniform distribution.
#' Each parameter value is multiplied by a random factor between (1 - jitter%) and (1 + jitter%) with boundary enforcement.
#' Examples: 0.1 (10% jitter on all params) or c("theta" = 0.05, "omega" = 0.1)
#' @param jitter_excluded character or character vector of parameter names to exclude from jittering.
#' Examples: "THETA1" or c("THETA1", "OMEGA(1,1)")
#' @param seed integer for random number generator seed to ensure reproducible jittering
#' @param description Description of model in metadata file
#' @param no_metadata boolean, if true, does not create metadatafile, default FALSE
#'
#' @return path to new model file (invisible) todo
#' @export
#'
#' @examples \dontrun{
#' copy_model(from = "model/nonmem/run001.mod", to = "model/nonmem/run002.mod")
#' }
copy_model <- function(from, to, overwrite = FALSE, ext_file = NULL, update = 'none', jitter = NULL, jitter_excluded = NULL, seed = NULL, description = NULL, no_metadata = FALSE) .Call(wrap__copy_model_wrap, from, to, overwrite, ext_file, update, jitter, jitter_excluded, seed, description, no_metadata)

#' Gets model run summary
#'
#' @param directory path to model run output directory containing .ext, .lst files
#' @param hide_off_diagonal_params boolean, if TRUE will not display the unfixed off-diagonal
#' estimated parameters
#'
#' @return hyperion_nonmem_summary S3 object
#' @export
#'
#' @examples \dontrun{
#' get_model_summary("model/nonmem/run001")
#' }
get_model_summary <- function(directory, hide_off_diagonal_params = FALSE) .Call(wrap__get_model_summary, directory, hide_off_diagonal_params)

#' Parses lst file for run details and heuristics
#'
#' @param path path to model file, model output directory, lst file or metadata json file.
#'
#' @return list of data.frames of run details and run heuristics
#' @export
#'
#' @examples \dontrun{
#' get_run_info("model/nonmem/run001/run001.lst")
#' }
get_run_info <- function(path) .Call(wrap__get_run_info, path)

#' Checks mod file for nmtran errors
#'
#' @param model_path path to nonmem model file
#'
#' @return NULL
#' @export
#'
#' @examples \dontrun{
#' check_model("model/nonmem/1001.mod")
#' }
check_model <- function(model_path) .Call(wrap__check_model_wrap, model_path)

#' Get's model lineage
#'
#' @param model_dir path to directory containing all models
#'
#' @return hyperion_nonmem_tree S3 object
#' @export
#'
#' @examples \dontrun{
#' get_model_lineage("model/nonmem/")
#' }
get_model_lineage <- function(model_dir) .Call(wrap__get_model_lineage, model_dir)

#' Gets parameter estimates from model run
#'
#' @param path path to model file, model output directory, ext file or metadata json file.
#' @param hide_off_diagonal_params boolean, if TRUE will not display the unfixed off-diagonal
#' estimated parameters
#' @param only_method character, filter for getting estimates from specified method only.
#' Available methods are Fo, Foce, Saems, Bayes, Imp, ImpMap, Its, Nuts
#' @param only_last boolean, for grabbing only last estimation method parameters
#' @param show_table_idx boolean, if TRUE include table_idx column in output
#' @param show_method boolean, if TRUE include method column in output
#'
#' @return data.frame of parameter estimates
#' @export
#'
#' @examples \dontrun{
#' get_parameters("model/nonmem/run001/run001.ext")
#' }
get_parameters <- function(path, hide_off_diagonal_params = FALSE, only_method = NULL, only_last = TRUE, show_table_idx = FALSE, show_method = FALSE) .Call(wrap__get_parameters, path, hide_off_diagonal_params, only_method, only_last, show_table_idx, show_method)

#' Gets parameter names from model for display purposes
#'
#' @param model hyperion_nonmem_model object from read_model()
#'
#' @return Named character vector with NONMEM names as names and user-friendly names as values
#' @export
#'
#' @examples \dontrun{
#' model <- read_model("run001.mod")
#' param_names <- get_model_parameter_names(model)
#' omega_names <- param_names[grepl("^OMEGA", names(param_names))]
#' }
get_model_parameter_names <- function(model) .Call(wrap__get_model_parameter_names, model)

#' Creates a metadata file for a NONMEM model
#'
#' This function creates a metadata file that stores information about a NONMEM model,
#' including its description, tags, and lineage information. The metadata is stored
#' in a structured format that can be used for model tracking and documentation.
#'
#' @param model_path Path to the NONMEM model file (required)
#' @param description Optional description of the model and its purpose
#' @param tags Character vector of tags to categorize or label the model
#' @param based_on Character vector of model names/paths that this model is based on
#'
#' @return Returns invisibly after creating the metadata file
#' @export
#'
#' @examples
#' \dontrun{
#' # Create basic metadata for a model
#' create_metadata_file("run001.mod", description = "Base population PK model")
#'
#' # Create metadata with tags and lineage
#' create_metadata_file(
#'   "run002.mod",
#'   description = "PK model with covariate effects",
#'   tags = c("population", "pk", "covariates"),
#'   based_on = c("run001.mod")
#' )
#'
#' # Overwrite existing metadata
#' create_metadata_file(
#'   "run001.mod",
#'   description = "Updated base model",
#'   overwrite = TRUE
#' )
#' }
set_metadata_file <- function(model_path, description = NULL, tags = NULL, based_on = NULL) .Call(wrap__set_metadata_file, model_path, description, tags, based_on)

#' Updates a metadatafile
#'
#' @param model_path path to model file or metadata file to update
#' @param description Optional description to add to metadata
#' @param tags Optional character vector of tags to add to tags field
#' @param based_on character vector of models to add to based_on field
#'
#' @return Invisibly after updaing
#' @export
#'
#' @examples \dontrun{
#' update_metadata_file("model/nonmem/run001.mod", tags = "key model")
#' update_metadata_file("model/nonmem/run004.mod", tags = "key model", based_on = "1002")
#' }
update_metadata_file <- function(model_path, description = NULL, tags = NULL, based_on = NULL) .Call(wrap__append_to_metadata_file, model_path, description, tags, based_on)

#' Reads ext file
#'
#' @param path path to model file, model output directory, ext file or metadata json file.
#' @param line_prefixes character vector for lines to filter for
#' @param parameters_only bool if true removes ITERATION and OBJ column, default false
#' @param only_method character, filter for getting estimates from specified method only
#' @param only_last boolean, for grabbing only last estimation method parameters
#'
#' @return data.frame of ext file
#' @export
#'
#' @examples \dontrun{
#' read_ext_file("model/nonmem/run001/run001.ext")
#' }
read_ext_file <- function(path, line_prefixes = NULL, parameters_only = FALSE, only_method = NULL, only_last = TRUE) .Call(wrap__read_ext_file, path, line_prefixes, parameters_only, only_method, only_last)

#' Gets all final estimates from an ext file or vector of ext files
#'
#' @param paths path to directory containing ext files (including subdirectories), single ext file, or vector of ext file paths
#' @param parameters_only bool if true removes ITERATION and OBJ column, default false
#' @param only_method character, filter for getting estimates from specified method only
#' @param only_last boolean, for grabbing only last estimation method parameters
#'
#' @return data.frame of final estimates with model names
#' @export
#'
#' @examples \dontrun{
#' get_final_estimates("model/nonmem/")
#' get_final_estimates("bootstrap/")  # Searches subdirectories recursively
#' get_final_estimates(c("run001.ext", "run002.ext", "run003.ext"))
#' }
get_final_estimates <- function(paths, parameters_only = TRUE, only_method = NULL, only_last = TRUE) .Call(wrap__get_final_estimates, paths, parameters_only, only_method, only_last)

#' Gets gradients of pararmeters during modeling
#'
#' @param path path to model file, model output directory, grd file or metadata json file.
#' @param only_method character, filter for getting estimates from specified method only.
#' Available methods are Fo, Foce, Saems, Bayes, Imp, ImpMap, Its, Nuts
#' @param only_last boolean, for grabbing only last estimation method parameters
#'
#' @return data.frame of gradients
#' @export
#'
#' @examples \dontrun{
#' get_gradients("model/nonmem/run001/run001.grd")
#' }
get_gradients <- function(path, only_method = NULL, only_last = TRUE) .Call(wrap__get_gradients, path, only_method, only_last)

#' Gets ETA shrinkage metrics from .shk file
#'
#' @param path path to model file, model output directory, shk file or metadata json file.
#'
#' @return data.frame of ETA shrinkage metrics
#' @export
#'
#' @examples \dontrun{
#' get_eta_shrinkage("model/nonmem/run001/run001.shk")
#' }
get_eta_shrinkage <- function(path) .Call(wrap__get_eta_shrinkage, path)

#' Gets EPS shrinkage metrics from .shk file
#'
#' @param path path to model file, model output directory, shk file or metadata json file.
#'
#' @return data.frame of EPS shrinkage metrics
#' @export
#'
#' @examples \dontrun{
#' get_eps_shrinkage("model/nonmem/run001/run001.shk")
#' }
get_eps_shrinkage <- function(path) .Call(wrap__get_eps_shrinkage, path)

#' Gets the pharos.toml configuration as an R object
#'
#' @return pharos config as nested list structure
#' @export
#'
#' @examples \dontrun{
#' config <- get_pharos_config()
#' config$nonmem$summary$high_correlation_threshold
#' config$nonmem$summary$high_condition_threshold
#' }
get_pharos_config <- function() .Call(wrap__get_pharos_config)

#' Get the comment type from pharos.toml config file
#'
#'
#' @return CommentType R object
#' @export
#'
#' @examples \dontrun{
#' get_comment_type()
#' }
get_comment_type <- function() .Call(wrap__get_comment_type_wrap)

#' Submits a NONMEM model to SLURM for execution
#'
#' This function submits a NONMEM model file to a SLURM cluster for execution,
#' allowing for parallel processing and job queue management. The function handles
#' job configuration, resource allocation, and job submission through pharos
#'
#' @param model Path to the NONMEM model file, or character vector of model paths/patterns (required)
#' @param overwrite Whether to overwrite existing output files (default: FALSE)
#' @param dry_run Whether to perform a dry run without actually submitting the job (default: FALSE)
#' @param run_in_output_dir Whether to run the job in the output directory (default: FALSE)
#' @param ncpu Number of CPUs to allocate for the job (default: 1)
#' @param partition SLURM partition to submit the job to (default: NULL, uses cluster default)
#' @param clean_level Level of cleanup to perform after job completion (default: 1)
#' @param parafile Path to parameter file for parallel runs (default: NULL)
#' @param template Path to SLURM template file for job submission (default: NULL)
#' @param account SLURM account to charge the job to (default: NULL)
#'
#' @return Returns invisibly after printing job submission results. Prints model path and corresponding SLURM job ID for each submitted job.
#' @export
#'
#' @examples
#' \dontrun{
#' # Submit a basic NONMEM model
#' submit_model_to_slurm("model.mod")
#'
#' # Dry run to test submission without actually running
#' submit_model_to_slurm("model.mod", dry_run = TRUE)
#'
#' # Submit to specific partition with account
#' submit_model_to_slurm("model.mod", partition = "gpu", account = "myproject")
#' }
submit_model_to_slurm <- function(model, overwrite = FALSE, dry_run = FALSE, run_in_output_dir = FALSE, ncpu = 1, partition = NULL, clean_level = 1, parafile = NULL, template = NULL, account = NULL) .Call(wrap__submit_model_to_slurm, model, overwrite, dry_run, run_in_output_dir, ncpu, partition, clean_level, parafile, template, account)

#' Submits a NONMEM model to SGE for execution
#'
#' This function submits a NONMEM model file to a SGE cluster for execution,
#' allowing for parallel processing and job queue management. The function handles
#' job configuration, resource allocation, and job submission through pharos
#'
#' @param model Path to the NONMEM model file, or character vector of model paths/patterns (required)
#' @param overwrite Whether to overwrite existing output files (default: FALSE)
#' @param dry_run Whether to perform a dry run without actually submitting the job (default: FALSE)
#' @param run_in_output_dir Whether to run the job in the output directory (default: FALSE)
#' @param ncpu Number of CPUs to allocate for the job (default: 1)
#' @param clean_level Level of cleanup to perform after job completion (default: 1)
#' @param parafile Path to parameter file for parallel runs (default: NULL)
#' @param template Path to SLURM template file for job submission (default: NULL)
#'
#' @return Returns invisibly after printing job submission results. Prints model path and corresponding SGE job ID for each submitted job.
#' @export
#'
#' @examples
#' \dontrun{
#' # Submit a basic NONMEM model
#' submit_model_to_sge("model.mod")
#'
#' # Dry run to test submission without actually running
#' submit_model_to_sge("model.mod", dry_run = TRUE)
#'}
submit_model_to_sge <- function(model, overwrite = FALSE, dry_run = FALSE, run_in_output_dir = FALSE, ncpu = 1, clean_level = 1, parafile = NULL, template = NULL) .Call(wrap__submit_model_to_sge, model, overwrite, dry_run, run_in_output_dir, ncpu, clean_level, parafile, template)


# nolint end
